# Generated by Django 2.0.1 on 2018-09-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staticscrumy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('moved_from', models.CharField(max_length=200)),
                ('moved_to', models.CharField(max_length=200)),
                ('time_of_action', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticscrumy.ScrumyGoals')),
            ],
        ),
    ]
