# Generated by Django 2.0.1 on 2018-09-08 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staticscrumy', '0002_remove_scrumygoals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
