# Generated by Django 2.0.1 on 2018-09-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtask',
            name='xpected',
            field=models.TextField(default='Nil'),
        ),
    ]
