# Generated by Django 2.0.1 on 2018-09-12 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(default='not graded', max_length=20)),
                ('course_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.CourseTopic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
