# Generated by Django 2.0.1 on 2018-09-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20180918_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesreport',
            name='task_no',
        ),
    ]
