# Generated by Django 2.0.7 on 2018-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('home', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=1000)),
            ],
        ),
    ]
